# 💻 Taller de Práctica: NumPy para Machine Learning

Este cuaderno contiene 8 ejercicios clave de Álgebra Lineal y manipulación de tensores con NumPy, esenciales para el desarrollo de Machine Learning e Inteligencia Artificial.

---


In [ ]:
import numpy as np
# Configuraciones iniciales
np.set_printoptions(precision=4, suppress=True)
print("NumPy importado exitosamente.")

## 1. Creación e Inspección de Tensores Básicos

**Contexto:** Antes de cualquier modelo, necesitas saber crear y entender la forma (shape) de tus datos.

**Tareas:**
1. Crea un vector `v` de 10 ceros y cambia el valor del quinto elemento (índice 4) a 1.
2. Crea una matriz `M` de 3x3 con valores del 0 al 8 (usa `np.arange` y `reshape`).
3. Imprime la forma (`shape`), el número de dimensiones (`ndim`) y el tipo de dato (`dtype`) de `M`.
4. Crea una matriz identidad de 3x3.


In [3]:
import numpy as np

In [5]:
v = np.zeros(10)
v[4] = 1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
m = np.arange(9).reshape(3, 3)
print(m)
print(m.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


In [ ]:
print("Forma (shape):", m.shape)
print("Dimensiones (ndim):", m.ndim)
print("Tipo de dato (dtype):", m.dtype)  

Forma (shape): (3, 3)
Dimensiones (ndim): 2
Tipo de dato (dtype): int64


## 2. Slicing y Indexación Avanzada (Extracción de Datos)

**Contexto:** A menudo necesitas separar features de etiquetas o dividir datasets.º

**Tareas:**
1. Crea una matriz `D` de 10x5 con números aleatorios (usa `np.random.rand`).
2. Selecciona y guarda en una variable `D_sub1` las primeras 3 filas completas.
3. Selecciona en `D_sub2` la segunda y cuarta columna de todas las filas.
4. (Bonus) Invierte el orden de las filas de la matriz `D` en `D_rev`.


In [4]:
np.random.seed(0) 
D = np.random.rand(10, 5)

print("--- Matriz Original D (Primeras 5 filas) ---")
print(D[:5]) # Solo imprimo 5 para no llenar la pantalla

# 2. Primeras 3 filas
D_sub1 = D[:3, :]
print("\n--- D_sub1 (Primeras 3 filas) ---")
print(D_sub1)

# 3. Segunda (idx 1) y Cuarta (idx 3) columna
D_sub2 = D[:, [1, 3]]
print("\n--- D_sub2 (Primeras 5 filas de col 2 y 4) ---")
print(D_sub2[:5]) 

# 4. Invertir filas
D_rev = D[::-1]
print("\n--- D_rev (Última fila original ahora es la primera) ---")
print(D_rev[:3]) # Vemos las primeras 3 del invertido

--- Matriz Original D (Primeras 5 filas) ---
[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]]

--- D_sub1 (Primeras 3 filas) ---
[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]]

--- D_sub2 (Primeras 5 filas de col 2 y 4) ---
[[0.71518937 0.54488318]
 [0.43758721 0.96366276]
 [0.52889492 0.92559664]
 [0.0202184  0.77815675]
 [0.79915856 0.78052918]]

--- D_rev (Última fila original ahora es la primera) ---
[[0.67063787 0.21038256 0.1289263  0.31542835 0.36371077]
 [0.3595079  0.43703195 0.6976312  0.06022547 0.66676672]
 [0.6176355  0.61209572 0.616934   0.94374808 0.6818203 ]]


## 3. Broadcasting en la Práctica (Operaciones Element-wise)

**Contexto:** Quieres ajustar pesos o aplicar bias sin usar bucles `for` lentos, lo cual es fundamental para el rendimiento.

**Tareas:**
1. Crea una matriz `A` de forma (4, 3) con valores aleatorios.
2. Crea un vector `b` de forma (3,).
3. Calcula `Suma = A + b`.
4. Intenta sumar un vector `c` de forma (4,) a `A`. Reformatea `c` a la forma (4, 1) para que funcione (usando `reshape` o `[:, np.newaxis]`) y realiza la suma en `Suma2`.


In [5]:
np.random.seed(42)

# --- Pasos 1, 2 y 3 ---
A = np.random.rand(4, 3)
b = np.arange(3)       # Vector [0, 1, 2]

Suma = A + b

print("Matriz A original:\n", A)
print("\nVector b:", b)
print("Suma (A + b) -> b se suma a cada fila:\n", Suma)

# --- Paso 4 ---
c = np.array([10, 20, 30, 40]) # Vector de 4 elementos

# Transformamos c de (4,) a (4, 1)
c_reshaped = c.reshape(4, 1)

Suma2 = A + c_reshaped

print("\nVector c reformateado a columna:\n", c_reshaped)
print("Suma2 (A + c_reshaped) -> c se suma a cada columna:\n", Suma2)

Matriz A original:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]]

Vector b: [0 1 2]
Suma (A + b) -> b se suma a cada fila:
 [[0.37454012 1.95071431 2.73199394]
 [0.59865848 1.15601864 2.15599452]
 [0.05808361 1.86617615 2.60111501]
 [0.70807258 1.02058449 2.96990985]]

Vector c reformateado a columna:
 [[10]
 [20]
 [30]
 [40]]
Suma2 (A + c_reshaped) -> c se suma a cada columna:
 [[10.37454012 10.95071431 10.73199394]
 [20.59865848 20.15601864 20.15599452]
 [30.05808361 30.86617615 30.60111501]
 [40.70807258 40.02058449 40.96990985]]


## 4. Operaciones de Agregación con Ejes (Reducción)

**Contexto:** Calcular métricas como el promedio de pérdidas o la desviación estándar por feature.

**Tareas:**
1. Crea una matriz `Data` de (5, 4) con valores aleatorios.
2. Calcula la **media** de toda la matriz en `mean_total`.
3. Calcula la **suma** de cada columna (a lo largo del eje 0) en `sum_cols`.
4. Encuentra el **valor máximo** de cada fila (a lo largo del eje 1) en `max_rows`.


In [7]:
np.random.seed(42)
Data = np.random.rand(5, 4)

print("--- Matriz Data (5x4) ---")
print(Data)

# 2. Media total
mean_total = Data.mean()
print(f"\nMedia total de la matriz: {mean_total:.4f}")

# 3. Suma por columnas (axis=0)
sum_cols = Data.sum(axis=0)
print("\n--- Suma de columnas (axis=0) ---")
print(f"Valores: {sum_cols}")
print(f"Forma resultante: {sum_cols.shape}") # Debería ser (4,)

# 4. Máximo por filas (axis=1)
max_rows = Data.max(axis=1)
print("\n--- Máximo de cada fila (axis=1) ---")
print(f"Valores: {max_rows}")
print(f"Forma resultante: {max_rows.shape}") # Debería ser (5,)

--- Matriz Data (5x4) ---
[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]]

Media total de la matriz: 0.4577

--- Suma de columnas (axis=0) ---
Valores: [2.26835865 2.55187695 1.42443203 2.90937813]
Forma resultante: (4,)

--- Máximo de cada fila (axis=1) ---
Valores: [0.95071431 0.86617615 0.96990985 0.83244264 0.52475643]
Forma resultante: (5,)


## 5. Filtrado con Máscaras Booleanas (Limpieza de Datos)

**Contexto:** Necesitas eliminar outliers o filtrar valores específicos, una técnica muy usada en preprocesamiento.

**Tareas:**
1. Genera un vector `arr` con 20 números aleatorios entre -10 y 10.
2. Crea una "máscara" booleana `mask` que sea `True` donde los valores de `arr` sean negativos.
3. Usa la máscara para reemplazar todos los valores negativos de `arr` por 0 (implementando una ReLU manual en su lugar).
4. Cuenta cuántos valores del array original eran mayores a 5.


In [8]:
np.random.seed(42)
arr = np.random.randint(-10, 11, 20)

# Guardamos copia para el punto 4
arr_original = arr.copy()

print("1. Array original:\n", arr)

# 2. Crear máscara
mask = arr < 0
print("\n2. Máscara (True donde es negativo):\n", mask)

# 3. Aplicar máscara (ReLU)
arr[mask] = 0
print("\n3. Array modificado (Negativos -> 0):\n", arr)

# 4. Contar mayores a 5 en el original
# Vemos el array original: [ 6, 9, 4, -3, -4, ... ]
conteo = np.sum(arr_original > 5)
print(f"\n4. Cantidad de valores > 5 en el original: {conteo}")

1. Array original:
 [-4  9  4  0 -3 10 -4  8  0  0 10 -7 -3 -8 10 -9  1 -5 -9 10]

2. Máscara (True donde es negativo):
 [ True False False False  True False  True False False False False  True
  True  True False  True False  True  True False]

3. Array modificado (Negativos -> 0):
 [ 0  9  4  0  0 10  0  8  0  0 10  0  0  0 10  0  1  0  0 10]

4. Cantidad de valores > 5 en el original: 6


## 6. Multiplicación Matricial vs Element-wise

**Contexto:** Diferenciar entre el producto de matrices (operación lineal) y el producto elemento a elemento (Hadamard).

**Tareas:**
1. Crea dos matrices `X` e `Y`, ambas de 3x3 (usa `np.arange` para tener valores predecibles).
2. Calcula el **producto punto** (multiplicación matricial) en `dot_product` (usa `@`).
3. Calcula el **producto elemento a elemento** en `element_wise_product` (usa `*`).


In [9]:
# 1. Crear matrices
X = np.arange(9).reshape(3, 3)
Y = np.arange(9).reshape(3, 3)

print("Matriz X (y Matriz Y son iguales):\n", X)

# 2. Producto Punto (@)
# Ejemplo cálculo celda [0,0]: (0*0) + (1*3) + (2*6) = 0 + 3 + 12 = 15
dot_product = X @ Y
print("\n--- Producto Punto (X @ Y) ---")
print(dot_product)

# 3. Producto Elemento a Elemento (*)
# Ejemplo cálculo celda [0,0]: 0 * 0 = 0
# Ejemplo cálculo celda [2,2]: 8 * 8 = 64
element_wise_product = X * Y
print("\n--- Producto Elemento a Elemento (X * Y) ---")
print(element_wise_product)

Matriz X (y Matriz Y son iguales):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

--- Producto Punto (X @ Y) ---
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]

--- Producto Elemento a Elemento (X * Y) ---
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


## 7. Manipulación de Dimensiones (Flatten y Reshape para CNNs/RNNs)

**Contexto:** Preparar imágenes para una red densa o adaptar tensores para capas convolucionales.

**Tareas:**
1. Crea un tensor aleatorio `imagenes` con forma `(10, 28, 28)` (Batch, Alto, Ancho).
2. Aplana las dimensiones espaciales para obtener una forma `(10, 784)` en `flattened`.
3. Añade una dimensión extra al final para representar el canal (blanco y negro), quedando `(10, 28, 28, 1)` en `reshaped_channel`.


In [10]:
# 1. Crear tensor
np.random.seed(42)
imagenes = np.random.rand(10, 28, 28)

print(f"1. Forma original: {imagenes.shape}")
# Salida: (10, 28, 28)

# 2. Aplanar (Flatten)
# Esto simula preparar los datos para una red neuronal densa (MLP)
flattened = imagenes.reshape(10, 784)

print(f"2. Forma aplanada: {flattened.shape}")
# Salida: (10, 784)

# 3. Añadir canal
# Esto simula preparar los datos para una red convolucional (CNN) en Keras/TensorFlow
reshaped_channel = imagenes.reshape(10, 28, 28, 1)

print(f"3. Forma con canal: {reshaped_channel.shape}")
# Salida: (10, 28, 28, 1)

1. Forma original: (10, 28, 28)
2. Forma aplanada: (10, 784)
3. Forma con canal: (10, 28, 28, 1)


## 8. Vectorización de una Función (Evitar Bucles)

**Contexto:** Implementar lógica condicional de manera eficiente sobre arrays grandes.

**Tareas:**
1. Define un array `x` con 10 números aleatorios (algunos positivos y algunos negativos).
2. Usa la función `np.where` para crear un array `output` donde: 
   - Si el valor en `x` es mayor a 0, se mantiene ese valor. 
   - Si el valor en `x` es menor o igual a 0, se reemplaza por el valor absoluto de ese número.


In [11]:
np.random.seed(42)

# 1. Definir array x con 10 números aleatorios (positivos y negativos)
# Usamos randn para distribución normal (centrada en 0), así garantizamos +/-
x = np.random.randn(10)

print("Array original x:\n", x)

# 2. Usar np.where para crear output
# Condición: x > 0
# Si es True: mantén x
# Si es False: usa np.abs(x) (o -x)
output = np.where(x > 0, x, np.abs(x))

print("\nArray output (todos positivos):\n", output)

Array original x:
 [ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
  1.57921282  0.76743473 -0.46947439  0.54256004]

Array output (todos positivos):
 [0.49671415 0.1382643  0.64768854 1.52302986 0.23415337 0.23413696
 1.57921282 0.76743473 0.46947439 0.54256004]


## 🎓 Fin de la Práctica

¡Excelente trabajo! Has cubierto la base de las operaciones de datos que se usan diariamente en el campo de ML/IA. ¡Sigue practicando!